import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from "react";


export default function Home({data}) {

  const [active, setActive] = useState(0);

  
  function CustomImage(src) {
    const [imageError, setImageError] = useState(false);
    return (
      <Image src={imageError ? "/404.png" : src } alt="" height={32} width={32} onError={() => setImageError(true)}/>
    );
  }

  return (
    <div>
      <Head>
        <title>Furvooooo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="overflow-x-auto relative">
          <table className=" w-full text-sm text-left text-gray-500 dark:text-gray-400">
              <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                  <tr>
                      <th scope="col" className="py-3 px-2 text-center">
                          <button>
                            #
                          </button>
                      </th>
                      <th scope="col" className="py-3 px-0  ">
                          
                      </th>
                      <th scope="col" className="py-3 px-1">
                          Club
                      </th>
                      <th scope="col" className="py-3 px-6">
                          PJ
                      </th>
                      <th scope="col" className="py-3 px-6">
                          G
                      </th>
                      <th scope="col" className="py-3 px-6">
                          E
                      </th>
                      <th scope="col" className="py-3 px-6">
                          P
                      </th>
                      <th scope="col" className="py-3 px-6">
                          GF
                      </th>
                      <th scope="col" className="py-3 px-6">
                          GC
                      </th>
                      <th scope="col" className="py-3 px-6">
                          DJ
                      </th>
                      <th scope="col" className="py-3 px-6">
                          Pts
                      </th>
                  </tr>
              </thead>
              <tbody>
                  {data.data[0].rank.map(item => (
                    <>
                      <tr key={item.id} className="cursor-pointer hover:bg-gray-900 bg-gray-800 border-b border-gray-700" onClick={() => setActive(item.id)}>
                          <td className='text-center bg-gray-900'>
                            {item.standing.position}
                          </td>
                          <td className='pl-0 text-center'>
                            {CustomImage(item.imageUrl)}
                          </td>
                          <td scope="row" className="py-4 pl-2 font-medium whitespace-nowrap text-white">
                            {item.name === "River" ? "Ribergüenza" : item.name}
                          </td>
                          <td className="py-4 px-6">
                            {item.standing.played}
                          </td>
                          <td className="py-4 px-6">
                            {item.standing.won}
                          </td>
                          <td className="py-4 px-6">
                            {item.standing.drawn}
                          </td>
                          <td className="py-4 px-6">
                            {item.standing.lost}
                          </td>
                          <td className="py-4 px-6">
                            {item.standing.for}
                          </td>
                          <td className="py-4 px-6">
                            {item.standing.against}
                          </td>
                          <td className="py-4 px-6">
                            {item.standing.for-item.standing.against}
                          </td>
                          <td className="py-4 px-6">
                            {item.standing.points}
                          </td>
                      </tr>
                      <tr key={item.id+846} role="tablist" className={active === item.id ? "table-row" : "hidden"}>
                        <td role="tab" colSpan="11">
                          <div role="tabpanel" className='w-full table bg-green-500 h-48'>
                            {item.name}
                          </div>
                        </td>
                      </tr>
                    </>
                  ))}

              </tbody>
          </table>
      </div>

    </div>
  )
}
export const getServerSideProps = async (context)=>{
  const res = await fetch("https://api.unidadeditorial.es/sports/v1/classifications/current/?site=2&type=10&tournament=0152")
  
  const data = await res.json()

  return {
    props:{
      data
    }
  }
}